### ISSUE TITLE
Error While running the script

### ISSUE THREAD

**Issue by VA2PE** [eddiez9/sans-ondemand-download#12]
When running the script, I hit the following error halfway trough:

```
Traceback (most recent call last):
  File "download.py", line 120, in <module>
    lesson_path.mkdir()
  File "C:\Users\SomeUser\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1281, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'FOR578 Cyber Threat Intelligence E01085885\\4. Collection Sources \\1. Collection Sources Introduction'
```

Any idea of what could be causing that?

**Comment by VA2PE** [comment]
Found the issue, username had some non standard character, seemsa to be causing the issue
